enum SocketEvent {
  Connection = "connection",
  Connect = "connect",
  Disconnect = "disconnect",
  CreateRoomAttempt = "createRoomAttempt",
  CreateRoomSuccess = "createRoomSuccess",
  CreateRoomError = "createRoomError",
  JoinRoomAttempt = 'joinRoom',
  JoinRoomSuccess = 'joinRoomSuccess',
  JoinRoomError = 'joinRoomError',
  Players = 'players',
  HostPlayerId = 'hostPlayerId',
  SetReadyStatusAttempt = 'setReadyStatusAttempt',
  SetReadyStatusSuccess = 'setReadyStatusSuccess',
  SetReadyStatusError = 'setReadyStatusError',
  PlayerSetReady = 'playerSetReady',
  ArePlayersReady = 'playersAreReady',
  StartGame = 'startGame',
  StartGameSuccess = 'startGameSuccess',
  GetQuestion = 'getQuestion',
  GetQuestionSuccess = 'getQuestionSuccess',
  Countdown = 'countdown',
  Answer = 'answer',
  ShowCorrectAnswer = 'showCorrectAnswer',
  Scores = 'scores',
};

export default SocketEvent;
